[project]
name = "mistral-ocr"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "img2pdf>=0.6.0",
    "markdown>=3.7",
    "md4mathjax>=0.1.3",
    "mistralai>=1.5.1",
    "pillow>=11.1.0",
    "pyqt5>=5.15.11",
    "pyqtwebengine>=5.15.7",
]
